version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - COMPOSER_AUTH=${COMPOSER_AUTH:-{}}
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: blog_db
      DB_USER: postgres
      DB_PASSWORD: secret

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/sample-data.sql:/docker-entrypoint-initdb.d/2-sample-data.sql

  node:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: npm run watch

volumes:
  pgdata: