services:
  - type: web
    name: blog-app
    runtime: docker
    branch: main
    buildCommand: ./build.sh
    startCommand: apache2-foreground
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

databases:
  - name: blog-db
    plan: free
    databaseName: blog_db
    user: postgres
    region: frankfurt  # Ücretsiz bölge
